version: "3.5"
services:
  chatgptbot:
    container_name: chatgptbot
    build: # 👈 Changed from 'image' to 'build'
      context: . # 👈 Specifies the current directory as the build context
      dockerfile: Dockerfile.build # 👈 Explicitly specifies the Dockerfile name (optional if named Dockerfile)
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API=${API}
      - API_URL=${API_URL}
      - CUSTOM_MODELS=${CUSTOM_MODELS}
      - GPT_ENGINE=${GPT_ENGINE}
      - ADMIN_LIST=${ADMIN_LIST}
      - GROUP_LIST=${GROUP_LIST}
      - whitelist=${whitelist}
      - NICK=${NICK}
      - SYSTEMPROMPT=${SYSTEMPROMPT}
    volumes:
      - ./user_configs:/home/user_configs
    ports:
      - 12349:8080